version: "3.9"

services:
  charging-ui:
    container_name: charging-ui
    image: charging/charging-ui:latest
    build: ../Charging-App/.
    ports:
      - 8080:8080
    environment:
      VITE_SERVICE_API_AUTH_URL: http://user-management:3000
      VITE_SERVICE_NOTIFICATION_URL: http://notifications:3000
      VITE_SERVICE_USER_MANAGEMENT_URL: http://user-management:3000
      VITE_SERVICE_CHARGING_EVENT_URL: http://charging-events:3000
      VITE_SERVICE_PAYMENT_URL: http://payments:3000
      VITE_STRIPE_PUBLISHABLE_KEY: pk_test_51O20pPGVeGfd6ixFmGvd6kyeVCSJFBO4d23pxSxPW14Gb50ItqtyhWS19uxYRJQTi3Ldwb5qzH4McVpiNEvp0c9W00vge9fr1M
      VITE_AWS_RUM_GUEST_ROLE_ARN: "arn:aws:iam::101265448075:role/RUM-Monitor-us-west-2-101265448075-7086450273961-Unauth"
      VITE_AWS_RUM_IDENTITY_POOL_ID: "us-west-2:1faab99b-11ab-4924-870b-a3a17dc0ccb3"
      VITE_AWS_RUM_APPLICATION_ID: "9df9af97-ea9a-431d-9d9d-602956ee56dd"
      VITE_CHARGE_STATUS_INTERVAL: 3000

  user-management:
    container_name: user-management
    image: charging/user-management:latest
    build: ../Charging-Microservices/user-management
    environment:
      SERVICE_API_AUTH_URL: http://user-management:3000
      SERVICE_NOTIFICATION_URL: http://nofitications:3000
      SERVICE_PAYMENT_URL: http://payments:3000
      HASH_SALT: 10
      TOKEN_SECRET_KEY: alskdjfalksdjf08230948234jlksdjflksjfd02938409324klsjdfsfd
      TRIAL_SUBSCRIPTION_CUSTOMERS: "480 417 9675,480 747 9384"
      SUBSCRIPTION_MONTHLY_FEE: 70
      SUBSCRIPTION_PROCESSING_CRON_SCHEDULE: "*/5 * * * *"
      CUSTOMER_PROCESSING_CRON_SCHEDULE: "*/10 * * * *"

      POSTGRES_HOST: stage-db-psql-charging-1.cizjbxfi5ccd.us-west-2.rds.amazonaws.com
            POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MD2P!JcBlktnGz!P]y5LG?r}o5k[
            POSTGRES_DB: nxuenergy
    ports:
      - 3003:3000
    depends_on:
      - postgres

  charging-events:
    container_name: charging-events
    image: charging/charging-events:latest
    build: ../Charging-Microservices/charging-event
    environment:
      SERVICE_USER_MANAGEMENT_URL: http://user-management:3000
      SERVICE_NOTIFICATION_URL: http://notifications:3000
      SERVICE_API_AUTH_URL: http://user-management:3000
      SERVICE_PAYMENT_URL: http://payments:3000
      SERVICE_CHARGING_IOT_URL: http://iot:80
      SERVICE_CHARGING_IOT_CHECK_CON_URL: http://iot:80
      SERVICE_CHARGING_IOT_MANAGE_CHG_URL: http://iot:80
      SERVICE_CHARGING_IOT_COMPLETE_CHG_URL: http://iot:80
      PROMO1_FROM_DATE: 09/28/2023
      PROMO1_TO_DATE: 10/01/2023

      POSTGRES_HOST: stage-db-psql-charging-1.cizjbxfi5ccd.us-west-2.rds.amazonaws.com
            POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MD2P!JcBlktnGz!P]y5LG?r}o5k[
            POSTGRES_DB: nxuenergy
    ports:
      - 3004:3000
    depends_on:
      - postgres

  notifications:
    container_name: notifications
    image: charging/notifications:latest
    build: ../Cloud-Microservices/notification
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nxuenergy

      TWILIO_ACCOUNT_SID: AC71c4af10c04b40c3a9443781ecf19a13
      TWILIO_AUTH_TOKEN: e5da14523c1de6ee0cfba33e71ab23ab
      TWILIO_PHONE_NUMBER: +12136992567
      SERVICE_API_AUTH_URL: http://user-management:3000
      SMTP_HOST: smtp.office365.com
      SMTP_PORT: 587
      SMTP_USERNAME: charging@nxuenergy.com
      SMTP_PASSWORD: insertpasswordhere
      FRONTEND_URL: http://charging-ui:8080
    ports:
      - 3002:3000

  payments:
    container_name: payments
    image: charging/payments:latest
    build: ../Cloud-Microservices/payment
    environment:
      SERVICE_API_AUTH_URL: http://user-management:3000
      STRIPE_API_KEY: sk_test_51O20pPGVeGfd6ixFMw9YktZTn57dtx8YqM1aJAzyD5LoNPbz6FNWyp2OkW4sVmCSkttXYEYv7QpeH34a6qepejz100DAWjZwaq
      SERVICE_USER_MANAGEMENT_URL: http://user-management:3000
    ports:
      - 3005:3000

  iot:
    container_name: iot
    image: clue/json-server
    ports:
      - 8083:80
    volumes:
      - ./iot-db.json:/data/db.json

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nxuenergy
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8082:80
