export const VALIDATION_ERROR_MESSAGE = {
  email_required: "Email is required.",
  email_invalid: "Email format is invalid.",
  password_required: "Password is required.",
  password_length: "Password length should be between 6 and 20.",
  password_notmatch: "Password does not match.",
  confirmPassword_required: "Confirm Password is required.",
  confirmPassword_length: "Confirm Password length should be between 6 and 20.",
  phonenumber_required: "Phone number is required.",
  phonenumber_invalid: "Phone number should look like xxx-xxx-xxxx.",
  firstname_required: "First Name is required.",
  lastname_required: "Last Name is required.",
  authcode_required: "AuthCode is required.",
  authcode_invalid: "AuthCode is invalid.",
  pincode_required: "PIN is required.",
  pincode_invalid: "PIN should be 4 digits.",
  pinconfirmcode_required: "Confirm PIN is required.",
  pinconfirmcode_invalid: "Confirm PIN should be 4 digits.",
  pincode_notmatch: "PIN and Confirm PIN should match.",
  stationid_required: "ChargerID is required.",
  stationid_invalid: "ChargerID is invalid.",
  cardnumber_required: "CardNumber is required.",
  cardnumber_invalid: "CardNumber is invalid.",
  cardexpdate_required: "Card Exp Date is required.",
  cardexpdate_invalid: "Card Exp Date is invalid.",
  cardcvv_required: "Card CVV is required.",
  cardcvv_invalid: "Card CVV is invalid.",
};
