export const VALIDATION_ERROR_MESSAGE = {
  email_required: "Email is required.",
  email_invalid: "Email format is invalid.",
  password_required: "Password is required.",
  password_length: "Password length should be between 6 and 20.",
  password_notmatch: "Password does not match.",
  confirmPassword_required: "Confirm Password is required.",
  confirmPassword_length: "Confirm Password length should be between 6 and 20.",
  phonenumber_required: "Phone number is required.",
  phonenumber_invalid: "Phone number should look like xxx-xxx-xxxx.",
  firstname_required: "First Name is required.",
  lastname_required: "Last Name is required.",
  authcode_required: "AuthCode is required.",
  authcode_invalid: "AuthCode is invalid.",
  pincode_required: "Password is required.",
  pincode_length: "Password length should be between 7 and 20",
  pincode_invalid:
    "Password should contain both numeric and alphabetic characters",
  pinconfirmcode_required: "Confirm Password is required.",
  pinconfirmcode_length: "Confirm Password length should be between 7 and 20",
  pinconfirmcode_invalid:
    "Confirm Password should contain both numeric and alphabetic characters",
  pincode_notmatch: "Password and Confirm Password should match.",
  stationid_required: "ChargerID is required.",
  stationid_invalid: "ChargerID is invalid.",
};
