export const VALIDATION_ERROR_MESSAGE = {
  email_required: "Email is required.",
  email_invalid: "Email format is name@example.com.",
  clear_whitespace: "Clear whitespace and/or special characters.",
  password_required: "Password is required.",
  password_length: "Password length should be between 6 and 20.",
  password_notmatch: "Password does not match.",
  confirmPassword_required: "Confirm Password is required.",
  confirmPassword_length: "Confirm Password length should be between 6 and 20.",
  phonenumber_required: "Phone number is required.",
  phonenumber_invalid: "Phone number format is xxx-xxx-xxxx.",
  firstname_required: "First Name is required.",
  lastname_required: "Last Name is required.",
  authcode_required: "SMS AuthCode is required.",
  authcode_invalid: "SMS AuthCode is invalid.",
  pincode_required: "Password is required.",
  pincode_length: "Password length must be at least 7 characters that include both numeric and alphabetic characters.",
  pincode_invalid:
    "Password length must be at least 7 characters that include both numeric and alphabetic characters.",
  pinconfirmcode_required: "Confirm Password is required.",
  pinconfirmcode_length: "Confirm Password length must be at least 7 characters that include both numeric and alphabetic characters.",
  pinconfirmcode_invalid:
    "Confirm Password length must be at least 7 characters that include both numeric and alphabetic characters.",
  pincode_notmatch: "Passwords do not match.",
  stationid_required: "ChargerID is required.",
  stationid_invalid: "Charger ID is invalid. Please confirm ID number on charger.",
};
